export type IndustryConfig = {
  serviceOptions: string[]
  highlights: string[]
  jobPlaceholder: string
  ratingLabels: { service: string; quality: string; speed: string }
}

const configs: Record<string, IndustryConfig> = {
  Plumbing: {
    serviceOptions: [
      'Leaking tap or pipe',
      'Blocked drain',
      'Hot water system',
      'Toilet repair or install',
      'Bathroom renovation',
      'Kitchen plumbing',
      'Gas fitting',
      'New installation',
      'Emergency call-out',
      'Other',
    ],
    highlights: [
      'Arrived on time',
      'Fixed it on the first visit',
      'Left no mess',
      'Explained the problem clearly',
      'Came out same day',
      'Good value for money',
      'Friendly & professional',
      'Kept us updated',
      'Easy to get in touch',
      'Sorted it quickly',
    ],
    jobPlaceholder: 'e.g. Fixed a burst pipe under the kitchen sink',
    ratingLabels: { service: 'Overall service', quality: 'Quality of work', speed: 'Response time' },
  },

  Electrical: {
    serviceOptions: [
      'Power points / outlets',
      'Lighting installation',
      'Switchboard / panel',
      'Safety inspection',
      'Air conditioning wiring',
      'Solar / battery',
      'Data & communications',
      'New build wiring',
      'Emergency fault',
      'Other',
    ],
    highlights: [
      'Arrived on time',
      'Explained everything clearly',
      'Tidy and no damage to walls',
      'Fixed it first time',
      'Safety-focused',
      'Good value for money',
      'Friendly & professional',
      'Came out same day',
      'Easy to communicate with',
      'Sorted it quickly',
    ],
    jobPlaceholder: 'e.g. Installed new downlights throughout the lounge and dining room',
    ratingLabels: { service: 'Overall service', quality: 'Quality of work', speed: 'Response time' },
  },

  'HVAC & Air Con': {
    serviceOptions: [
      'Split system install',
      'Ducted system install',
      'AC service / clean',
      'AC repair',
      'Heating system',
      'Ventilation',
      'Commercial HVAC',
      'Other',
    ],
    highlights: [
      'Arrived on time',
      'Explained the system clearly',
      'Clean and tidy',
      'Fixed it first visit',
      'Came out same day',
      'Good value for money',
      'Friendly & professional',
      'Ran us through how to use it',
      'Fast installation',
      'Sorted it quickly',
    ],
    jobPlaceholder: 'e.g. Installed a new 7kW split system in the main bedroom',
    ratingLabels: { service: 'Overall service', quality: 'Installation quality', speed: 'Response time' },
  },

  'Building & Construction': {
    serviceOptions: [
      'New home build',
      'Extension',
      'Renovation',
      'Deck or pergola',
      'Garage or shed',
      'Bathroom',
      'Kitchen',
      'Structural work',
      'Other',
    ],
    highlights: [
      'Kept to the schedule',
      'Great quality finish',
      'Kept the site clean',
      'Communicated throughout',
      'Transparent with costs',
      'Attention to detail',
      'Friendly & professional',
      'Sorted problems quickly',
      'Delivered on the vision',
      'No surprises',
    ],
    jobPlaceholder: 'e.g. Built a new deck and pergola at the back of our house',
    ratingLabels: { service: 'Overall experience', quality: 'Quality of work', speed: 'Kept to schedule' },
  },

  Painting: {
    serviceOptions: [
      'Interior walls & ceilings',
      'Exterior',
      'Fence or gate',
      'Deck or timber',
      'Kitchen cabinets',
      'Commercial',
      'Touch-ups',
      'Other',
    ],
    highlights: [
      'Arrived on time',
      'Clean crisp lines',
      'Protected floors and furniture',
      'Great colour advice',
      'Neat and tidy',
      'Good value for money',
      'Friendly & professional',
      'Finished on time',
      'No drips or mess',
      'Transformed the space',
    ],
    jobPlaceholder: 'e.g. Painted the full interior of our 4-bedroom house',
    ratingLabels: { service: 'Overall service', quality: 'Quality of finish', speed: 'Finished on time' },
  },

  Landscaping: {
    serviceOptions: [
      'Lawn mowing & edging',
      'Garden design',
      'Retaining walls',
      'Irrigation system',
      'Tree removal or trimming',
      'Paving or paths',
      'Turf laying',
      'Clean-up',
      'Other',
    ],
    highlights: [
      'Arrived on time',
      'Transformed the yard',
      'Left it spotless',
      'Great design ideas',
      'Good value for money',
      'Friendly & professional',
      'Finished on time',
      'Hard working',
      'Listened to what we wanted',
      'High quality plants and materials',
    ],
    jobPlaceholder: 'e.g. Laid new turf and built a retaining wall along the back fence',
    ratingLabels: { service: 'Overall service', quality: 'Quality of work', speed: 'Finished on time' },
  },

  Cleaning: {
    serviceOptions: [
      'Regular home clean',
      'End of lease clean',
      'Spring clean',
      'Carpet cleaning',
      'Window cleaning',
      'Pressure washing',
      'Commercial clean',
      'Other',
    ],
    highlights: [
      'Arrived on time',
      'Left it spotless',
      'Paid attention to the details',
      'Brought their own supplies',
      'Good value for money',
      'Friendly & professional',
      'Trustworthy',
      'Flexible with timing',
      'Easy to book',
      'Thorough job',
    ],
    jobPlaceholder: 'e.g. End of lease clean on a 3-bedroom apartment',
    ratingLabels: { service: 'Overall service', quality: 'Cleanliness', speed: 'Time taken' },
  },

  Healthcare: {
    serviceOptions: [
      'GP consultation',
      'Specialist appointment',
      'Physiotherapy',
      'Chiropractic',
      'Dental',
      'Allied health',
      'Mental health',
      'Other',
    ],
    highlights: [
      'Listened carefully',
      'Explained everything clearly',
      'Made me feel at ease',
      'Minimal wait time',
      'Very thorough',
      'Caring and empathetic',
      'Professional',
      'Easy to get an appointment',
      'Followed up after',
      'Great outcome',
    ],
    jobPlaceholder: 'e.g. Initial assessment and treatment for a shoulder injury',
    ratingLabels: { service: 'Overall care', quality: 'Standard of care', speed: 'Wait time' },
  },

  Hospitality: {
    serviceOptions: [
      'Dine in',
      'Takeaway / delivery',
      'Private function',
      'Catering',
      'Accommodation',
      'Bar',
      'Other',
    ],
    highlights: [
      'Great food',
      'Excellent service',
      'Warm and welcoming',
      'Good value for money',
      'Great atmosphere',
      'Fast service',
      'Generous portions',
      'Attentive staff',
      'Clean and comfortable',
      'Will definitely return',
    ],
    jobPlaceholder: 'e.g. Birthday dinner for 10 people — 3-course set menu',
    ratingLabels: { service: 'Overall experience', quality: 'Food & drink quality', speed: 'Service speed' },
  },

}

// Fallback for unknown or "Other" industries
const defaultConfig: IndustryConfig = {
  serviceOptions: [
    'General service',
    'Repair or fix',
    'Installation',
    'Consultation',
    'Maintenance',
    'Emergency call-out',
    'Other',
  ],
  highlights: [
    'Arrived on time',
    'Left the area clean',
    'Explained the problem clearly',
    'Fixed it quickly',
    'Good value for money',
    'Friendly & professional',
    'Great quality finish',
    'Easy to communicate with',
    'Sorted it in one visit',
    'Kept us updated throughout',
  ],
  jobPlaceholder: 'e.g. Briefly describe what we did for you',
  ratingLabels: { service: 'Overall service', quality: 'Quality of work', speed: 'Response speed' },
}

export function getSurveyConfig(industry: string | null): IndustryConfig {
  if (!industry) return defaultConfig
  return configs[industry] ?? defaultConfig
}
